# Generated by Django 5.2.14 on 2026-05-25 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP ERP (Fuel & Procurement)'), ('UTILITY', 'Utility Portal (Electricity)'), ('TRAVEL', 'Corporate Travel (Flights, Hotels, Ground)')], max_length=20)),
                ('category', models.CharField(max_length=255)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('factor', models.DecimalField(decimal_places=6, max_digits=12)),
                ('unit', models.CharField(max_length=50)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('facility_code', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel & Procurement'), ('UTILITY', 'Utility Portal Electricity'), ('TRAVEL', 'Corporate Travel Platform')], max_length=20)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('category', models.CharField(max_length=255)),
                ('activity_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit', models.CharField(max_length=50)),
                ('original_quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('original_unit', models.CharField(max_length=50)),
                ('co2e_emissions', models.DecimalField(decimal_places=6, max_digits=15)),
                ('emission_factor_used', models.DecimalField(decimal_places=6, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved & Locked'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('anomaly_flags', models.JSONField(blank=True, default=dict)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_activities', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='ingestion.facility')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Record Normalization'), ('UPDATE', 'Record Edited'), ('APPROVE', 'Record Approved'), ('REJECT', 'Record Rejected'), ('OVERRIDE', 'Calculations Overridden')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(default=dict)),
                ('activity_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='ingestion.activityrecord')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel & Procurement'), ('UTILITY', 'Utility Portal Electricity'), ('TRAVEL', 'Corporate Travel Platform')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Processing'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Successfully Processed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('error_summary', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ingestion.tenant')),
            ],
            options={
                'verbose_name_plural': 'Ingestion Batches',
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField()),
                ('raw_payload', models.JSONField()),
                ('status', models.CharField(choices=[('UNPROCESSED', 'Unprocessed'), ('VALIDATED', 'Validated & Normalized'), ('ERROR', 'Error Parsing')], default='UNPROCESSED', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.ingestionbatch')),
            ],
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='raw_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='ingestion.rawrecord'),
        ),
        migrations.AddField(
            model_name='facility',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='ingestion.tenant'),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='ingestion.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('tenant', 'facility_code')},
        ),
    ]
